### ISSUE TITLE
Can'tbuild ebcause of lbsd dependency

### ISSUE THREAD

**Issue by matklad** [cshuaimin/scd#1]
Hi!

I've tried building this locally on NixOS, but the build failed with `ld.lld: error: unable to find library -lbsd`. Could perchance this dep be made optional? If not, it might be a good idea to specify this dependency in readme.

**Comment by cshuaimin** [comment]
Currently I use `strmode()` from libbsd to convert file modes to symbolic notations. Maybe we can rewrite it?

**Comment by matklad** [comment]
https://docs.rs/strmode/1.0.0/strmode/ exists. Have no idea if it's any good

**Comment by cshuaimin** [comment]
Looks exactly what I want. Thank you!

**Comment by cshuaimin** [comment]
Should be fixed in 11d198c.

**Comment by matklad** [comment]
Works perfectly, thanks!

![image](https://user-images.githubusercontent.com/1711539/80713812-5ae79080-8af4-11ea-8550-94008db1d550.png)

Btw, if you want to bring this further (as in, write your own shell), you might find my thoughts interesting: https://matklad.github.io/2019/11/16/a-better-shell.html :-) 

The TL;DR is that I'd really love to see this kind of text UIs just built into a thing I use to make my computers do stuff.

**Comment by cshuaimin** [comment]
Great post. In order to improve the command line environment, there are indeed many areas that need improvement. But, uh, writing my own shell is too challenging for me.. Anyway, I'm just a newbie in Rust and programming.

However, I will continuing work on small things like this project, and hope it will make people's lives easier a little.
